### PR TITLE
Add domains and email generator

### PR DESCRIPTION
**Pull request by mac2000**
There may be a need to generate emails from time to time so here you go (added code and test)

Also - top 500 domains from alexa.com added

Script to take fresh list:

```
$domains = @()
$pages = 0..19
foreach($page in $pages) {
    $response = Invoke-WebRequest -Uri ('http://www.alexa.com/topsites/global;' + $page) -UseBasicParsing
    $domains += $response.Links | Where-Object href -Like '/siteinfo/*' | Select-Object @{n='Domain';e={ $_.href -replace '/siteinfo/', '' }}
    Start-Sleep -Seconds 1
    Write-Progress -Activity 'Retrieving top domains' -Status ('Page ' + $page) -PercentComplete ([Array]::IndexOf($pages, $page) / $pages.Count * 100)
}

$domains | Sort-Object Domain -Unique | Select-Object -ExpandProperty Domain | Add-Content (Join-Path -Path ([Environment]::GetFolderPath('Desktop')) -ChildPath 'domains.txt')
```

Domains may be used later on to generate urls also.

### CODE REVIEW

**Comment by mac2000** [comment]
Probably later on email generator may be modified to generate mail like:

```
[firstName]@[domain]
[lastName]@[domain]
[firstName][YYYY]@[domain]
```

and so on...

**Comment by mathieubrun** [comment]
Thank you for your feedback !

However I don't feel too comfortable putting real domain names for the sample data. I'd prefer using the fake company names.

Please tell me if you'd like to do it :)

**Comment by mac2000** [comment]
Seems tSeems to be reasonable, here is yet another commito be reasonable, here is yet another commit

**Comment by mathieubrun** [comment]
Thanks, merged !

**Pull request merged**
